In [ ]:
%pip install pandas numpy matplotlib seaborn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Reading the dataset

In [12]:
df = pd.read_csv('/Users/devammpatel/Desktop/Consumer_Shopping_Trend/Dataset/Consumer_Shopping_Trends_2026 (6).csv')
df.head()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level,gender,city_tier,shopping_preference
0,56,221111,6.5,12,0.7,1,6,16,16,28551,...,7,7,1,3,6,5,2,Other,Tier 3,Store
1,69,96029,8.2,13,2.7,6,9,14,1,124056,...,3,4,9,6,8,1,7,Male,Tier 3,Hybrid
2,46,19055,6.4,4,2.1,10,8,2,0,81939,...,4,10,1,1,3,3,3,Female,Tier 3,Store
3,32,53170,6.4,11,0.7,2,10,20,3,35901,...,10,2,4,8,2,6,6,Female,Tier 1,Store
4,60,244016,6.0,5,0.7,2,5,18,16,131971,...,2,5,8,9,7,1,6,Male,Tier 3,Store

In [12]:
df.tail()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level,gender,city_tier,shopping_preference
11784,67,151087,10.4,4,2.2,2,5,42,4,70860,...,9,9,7,2,8,7,6,Other,Tier 1,Store
11785,60,243273,6.1,10,3.0,3,2,20,14,90420,...,4,7,10,8,2,1,10,Female,Tier 2,Store
11786,53,154729,4.6,13,1.8,8,2,11,15,18700,...,5,9,1,3,4,6,1,Female,Tier 2,Store
11787,65,66116,6.2,3,1.0,1,1,31,0,61475,...,1,7,10,10,2,2,9,Other,Tier 1,Store
11788,34,168023,4.7,11,2.6,4,2,46,7,24532,...,4,4,5,2,5,2,6,Female,Tier 1,Store

In [13]:
df.isnull().sum()

age                            0
monthly_income                 0
daily_internet_hours           0
smartphone_usage_years         0
social_media_hours             0
online_payment_trust_score     0
tech_savvy_score               0
monthly_online_orders          0
monthly_store_visits           0
avg_online_spend               0
avg_store_spend                0
discount_sensitivity           0
return_frequency               0
avg_delivery_days              0
delivery_fee_sensitivity       0
free_return_importance         0
product_availability_online    0
impulse_buying_score           0
need_touch_feel_score          0
brand_loyalty_score            0
environmental_awareness        0
time_pressure_level            0
gender                         0
city_tier                      0
shopping_preference            0
dtype: int64

In [15]:
df.shape

(11789, 25)

In [16]:
df.describe()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,return_frequency,avg_delivery_days,delivery_fee_sensitivity,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level
count,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,...,11789.00000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000,11789.000000
mean,48.729409,131704.282382,6.011367,7.597930,2.514471,5.498770,5.534312,24.677581,9.482144,74554.929341,...,4.46747,3.999661,5.468827,5.462041,5.518704,5.486386,5.485368,5.532021,5.448554,5.504114
std,17.899445,68120.726684,1.976811,4.011628,1.263047,2.880366,2.887251,14.431277,5.728825,43167.126595,...,2.88545,1.995881,2.870195,2.882177,2.867613,2.877918,2.877264,2.848796,2.872740,2.876561
min,18.000000,15005.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,523.000000,...,0.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,33.000000,72450.000000,4.600000,4.000000,1.600000,3.000000,3.000000,12.000000,5.000000,36797.000000,...,2.00000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
50%,49.000000,131916.000000,6.000000,8.000000,2.500000,5.000000,6.000000,25.000000,9.000000,74859.000000,...,4.00000,4.000000,5.000000,5.000000,6.000000,5.000000,5.000000,6.000000,5.000000,6.000000
75%,64.000000,190505.000000,7.400000,11.000000,3.400000,8.000000,8.000000,37.000000,14.000000,112134.000000,...,7.00000,6.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000
max,79.000000,249989.000000,12.000000,14.000000,6.000000,10.000000,10.000000,49.000000,19.000000,149996.000000,...,9.00000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11789 entries, 0 to 11788
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   age                          11789 non-null  int64
 1   monthly_income               11789 non-null  int64
 2   daily_internet_hours         11789 non-null  float64
 3   smartphone_usage_years       11789 non-null  int64
 4   social_media_hours           11789 non-null  float64
 5   online_payment_trust_score   11789 non-null  int64
 6   tech_savvy_score             11789 non-null  int64
 7   monthly_online_orders        11789 non-null  int64
 8   monthly_store_visits         11789 non-null  int64
 9   avg_online_spend             11789 non-null  int64
 10  avg_store_spend              11789 non-null  int64
 11  discount_sensitivity         11789 non-null  int64
 12  return_frequency             11789 non-null  int64
 13  avg_delivery_days            11789 non-null  int64
 14  delivery_fee_sensitivity     11789 non-null  int64
 15  free_return_importance       11789 non-null  int64
 16  product_availability_online  11789 non-null  int64
 17  impulse_buying_score         11789 non-null  int64
 18  need_touch_feel_score        11789 non-null  int64
 19  brand_loyalty_score          11789 non-null  int64
 20  environmental_awareness      11789 non-null  int64
 21  time_pressure_level          11789 non-null  int64
 22  gender                       11789 non-null  str
 23  city_tier                    11789 non-null  str
 24  shopping_preference          11789 non-null  str
dtypes: float64(2), int64(20), str(3)
memory usage: 2.2 MB

In [18]:
df.columns

Index(['age', 'monthly_income', 'daily_internet_hours',
       'smartphone_usage_years', 'social_media_hours',
       'online_payment_trust_score', 'tech_savvy_score',
       'monthly_online_orders', 'monthly_store_visits', 'avg_online_spend',
       'avg_store_spend', 'discount_sensitivity', 'return_frequency',
       'avg_delivery_days', 'delivery_fee_sensitivity',
       'free_return_importance', 'product_availability_online',
       'impulse_buying_score', 'need_touch_feel_score', 'brand_loyalty_score',
       'environmental_awareness', 'time_pressure_level', 'gender', 'city_tier',
       'shopping_preference'],
      dtype='str')

In [19]:
df[df.duplicated()]

Empty DataFrame
Columns: [age, monthly_income, daily_internet_hours, smartphone_usage_years, social_media_hours, online_payment_trust_score, tech_savvy_score, monthly_online_orders, monthly_store_visits, avg_online_spend, avg_store_spend, discount_sensitivity, return_frequency, avg_delivery_days, delivery_fee_sensitivity, free_return_importance, product_availability_online, impulse_buying_score, need_touch_feel_score, brand_loyalty_score, environmental_awareness, time_pressure_level, gender, city_tier, shopping_preference]
Index: []

[0 rows x 25 columns]

In [21]:
df['gender'].unique()

<StringArray>
['Other', 'Male', 'Female']
Length: 3, dtype: str

In [22]:
df['gender'].value_counts()

gender
Male      3966
Female    3931
Other     3892
Name: count, dtype: int64

In [6]:
## Encoding gender values using label encoding
%pip install scikit-learn   
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

Requirement already satisfied: scikit-learn in /Users/devammpatel/Desktop/Consumer_Shopping_Trend/venv/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Users/devammpatel/Desktop/Consumer_Shopping_Trend/venv/lib/python3.14/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in /Users/devammpatel/Desktop/Consumer_Shopping_Trend/venv/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Users/devammpatel/Desktop/Consumer_Shopping_Trend/venv/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/devammpatel/Desktop/Consumer_Shopping_Trend/venv/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [31]:
gender_encoded = lbl_encoder.fit_transform(df['gender'])

array([2, 1, 0, ..., 0, 2, 0], shape=(11789,))

In [35]:
df['gender_encoded'] = gender_encoded
df.drop('gender', inplace=True, axis=1)
df.head()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level,city_tier,shopping_preference,gender_encoded
0,56,221111,6.5,12,0.7,1,6,16,16,28551,...,7,7,1,3,6,5,2,Tier 3,Store,2
1,69,96029,8.2,13,2.7,6,9,14,1,124056,...,3,4,9,6,8,1,7,Tier 3,Hybrid,1
2,46,19055,6.4,4,2.1,10,8,2,0,81939,...,4,10,1,1,3,3,3,Tier 3,Store,0
3,32,53170,6.4,11,0.7,2,10,20,3,35901,...,10,2,4,8,2,6,6,Tier 1,Store,0
4,60,244016,6.0,5,0.7,2,5,18,16,131971,...,2,5,8,9,7,1,6,Tier 3,Store,1

In [36]:
df['city_tier'].value_counts()

city_tier
Tier 1    3982
Tier 3    3949
Tier 2    3858
Name: count, dtype: int64

In [ ]:
## Encoding city_tier values using label encoding
df['city_tier_encoded'] = lbl_encoder.fit_transform(df['city_tier'])
df.drop('city_tier', inplace=True, axis=1)

In [43]:
df.head()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level,shopping_preference,gender_encoded,city_tier_encoded
0,56,221111,6.5,12,0.7,1,6,16,16,28551,...,7,7,1,3,6,5,2,Store,2,2
1,69,96029,8.2,13,2.7,6,9,14,1,124056,...,3,4,9,6,8,1,7,Hybrid,1,2
2,46,19055,6.4,4,2.1,10,8,2,0,81939,...,4,10,1,1,3,3,3,Store,0,2
3,32,53170,6.4,11,0.7,2,10,20,3,35901,...,10,2,4,8,2,6,6,Store,0,0
4,60,244016,6.0,5,0.7,2,5,18,16,131971,...,2,5,8,9,7,1,6,Store,1,2

In [49]:
# tier 1 = 0, tier 2 = 1, tier 3 = 2
df['city_tier_encoded'].value_counts()

city_tier_encoded
0    3982
2    3949
1    3858
Name: count, dtype: int64

In [45]:
df['shopping_preference'].value_counts()

shopping_preference
Store     10244
Online     1176
Hybrid      369
Name: count, dtype: int64

In [46]:
## Encoding shopping_preference values using label encoding
df['shopping_preference_encoded'] = lbl_encoder.fit_transform(df['shopping_preference'])
df.drop('shopping_preference', inplace=True, axis=1)
df.head()

,age,monthly_income,daily_internet_hours,smartphone_usage_years,social_media_hours,online_payment_trust_score,tech_savvy_score,monthly_online_orders,monthly_store_visits,avg_online_spend,...,free_return_importance,product_availability_online,impulse_buying_score,need_touch_feel_score,brand_loyalty_score,environmental_awareness,time_pressure_level,gender_encoded,city_tier_encoded,shopping_preference_encoded
0,56,221111,6.5,12,0.7,1,6,16,16,28551,...,7,7,1,3,6,5,2,2,2,2
1,69,96029,8.2,13,2.7,6,9,14,1,124056,...,3,4,9,6,8,1,7,1,2,0
2,46,19055,6.4,4,2.1,10,8,2,0,81939,...,4,10,1,1,3,3,3,0,2,2
3,32,53170,6.4,11,0.7,2,10,20,3,35901,...,10,2,4,8,2,6,6,0,0,2
4,60,244016,6.0,5,0.7,2,5,18,16,131971,...,2,5,8,9,7,1,6,1,2,2

In [50]:
## Store = 0, Online = 1, Hybrid = 2
df['shopping_preference_encoded'].value_counts()

shopping_preference_encoded
2    10244
1     1176
0      369
Name: count, dtype: int64

In [51]:
df.to_csv('/Users/devammpatel/Desktop/Consumer_Shopping_Trend/Dataset/Consumer_Shopping_Trends_2026_updated.csv', index=False)